spring.application.name=GharSeGharTakBackend
# MySQL DB connection
spring.datasource.url=jdbc:mysql://localhost:3306/login_db
spring.datasource.username=root
spring.datasource.password=shruti

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# CORS config (important for frontend)
spring.mvc.cors.allowed-origins=http://localhost:3000
spring.mvc.cors.allowed-methods=*

